[build]
  command = "npx pnpm build"
  publish = "build/"

[functions]
  node_bundler = "esbuild" # temporary workaround for https://github.com/sveltejs/kit/issues/6462

[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; object-src 'none'; script-src 'self'; style-src 'self'"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = '''
      max-age=31536000;
      includeSubDomains
    '''
    Permissions-Policy = '''
      accelerometer=(),
      autoplay=(),
      camera=(),
      encrypted-media=(),
      fullscreen=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      usb=()
    '''